### ISSUE TITLE
Question: Available as custom repository for add-on

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#1]
Hey

Good work, just a question, are you going to add it to HACS too? Or as a custom repository in HACS? 
Would be more easy for us to keep up to date with new updates/fixed and makes it easier to install

thnx for the effor

**Comment by mrbarbz** [comment]
Adding it to HACS would be great

**Comment by pergolafabio** [comment]
yeah , is easier to keep on track with updates

@vanackej , is that something you can do ?

btw, still running your addon, its verry stable if its running, no restart needed, no socket destroyed messages
only if i do a restart, that ticket is still open

nice work

**Comment by vanackej** [comment]
https://hacs.xyz/docs/faq/addons
HACS has nothing to do with addons.

But yeah, packaging this as an addon would maybe be great, but I see
several steps to make it right:
- MQTT configuration should be automatic for those using HA MQTT Addon.
- Network port opening for proxy mode

Maybe more. I never packaged HA addons and won't use one for my local
deployment. I also don't use HA MQTT Addon so I won't be able to test.

@pergolafabio Please share a zip file with the content you initiated to
make it available as an addon. I'll have a look.



Le ven. 14 janv. 2022 à 11:10, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
I missed this one , so it's available on custom hacs now?

https://github.com/vanackej/risco-mqtt-local/commit/26f5c03620f56f30968d9a17ae0a9389caf6118f

**Comment by pergolafabio** [comment]
![Screenshot_20220201-065028](https://user-images.githubusercontent.com/43251136/151919332-69fd6d42-8667-4019-bf56-2dc98b19a4ed.jpg)


W00t, thnx for this, appreciated :-)


Now it's easy to stay up to date... Strange that I see there 0.3.2, while you are already on 0.3.4 ?

**Comment by pergolafabio** [comment]
Ok, seems not ready yet :-)

![Screenshot_20220201-065507](https://user-images.githubusercontent.com/43251136/151919678-865fb50f-58c7-4f66-bdef-aa840e4a6c95.jpg)

**Comment by vanackej** [comment]
Home assistant addon configuration system is a pain. I tried to make it
work for a while, but it has serious limitations. It currently doesn't
allow more than 2 levels nesting in yaml/json and has no dynamic keys
support, which are required to fully support current configuration format
For now I gave up since I have no more time to spend on this, and this is
not a top priority for the project right now

Le mar. 1 févr. 2022 à 06:55, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ah, thnx for feedback, ok, then i didnt do anything wrong
i know someone who is verry familiar with writing add-ons and docker...

if you want i can ask if he wants to have a look and submit a PR?

**Comment by vanackej** [comment]
I'm definitely open to contributions in this area, yes. Feel free !

Le mar. 1 févr. 2022 à 09:47, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok, so the problem is actually that you also want define the mqtt stuff ?

**Comment by vanackej** [comment]
Not only, but yes, event for MQTT definition addon configuration system is
a problem.
Another issue is the way to customize zones settings : default
configuration and by zone name. It requires dynamic keys definition (the
zone name).

Le mar. 1 févr. 2022 à 09:51, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok, i'll ask when i see him on discord, are you there too btw?

**Comment by vanackej** [comment]
Generally not on discord, but if you give me a link I could come there
sometimes to have a discussion

Le mar. 1 févr. 2022 à 10:12, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok , i'll get in toch with him, so he can respond here to discuss it further

thnx, appreciated!

**Comment by pergolafabio** [comment]
hey , appriacted for doing this!!

**Comment by llambkin** [comment]
Hey guys. Pretty keen on testing this through HA. I have a Risco system, and I can't seem to get the docker container working through Unraid.

It just throws up this error:
node:internal/modules/cjs/loader:936
throw err;
^

Error: Cannot find module '/usr/src/app/dist/main.js'

at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
at node:internal/main/run_main_module:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}

**Comment by vanackej** [comment]
Your setup is not very clear to me.
At least provide the docker command you used to run it

**Comment by pergolafabio** [comment]
Maybe indeed wait so you add it as an add-on later, will be easier for everyone...

@vanackej , is the new PR helpfull?

**Comment by vanackej** [comment]
It should be, but I don't have time right now to review it. Probably by the end of the week.

**Comment by llambkin** [comment]
> Your setup is not very clear to me. At least provide the docker command you used to run it

Sorry mate, I just added the github link to Unraid as a docker, I don't know what Unraid uses as a command to run it. The error message is from Unraid's docker container logs.

**Comment by pergolafabio** [comment]
Hi, can you make a seperate issue, it's not related to this ticket

**Comment by vanackej** [comment]
Hi @pergolafabio , have you tried to run the addon code pushed by @felipecrs ?

**Comment by pergolafabio** [comment]
hi, no yet, i dont think i can do it? i think you need merge it right? Because its downloading still the old config when i readd it

**Comment by felipecrs** [comment]
https://developers.home-assistant.io/docs/add-ons/testing/

If you want to test before it gets merged, you need to clone it to your /local. The VS Code add-on can help you a lot in doing that.

**Comment by pergolafabio** [comment]
Hmm, not sure if i can do that, i run HassOS

**Comment by vanackej** [comment]
That's totally out of your HassOS install. It's a dev environment based on
vscode and docker containers that is totally isolated from your own HA
setup.

Le ven. 4 févr. 2022 à 13:56, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
hmm , i need todo some reading?
are you able to push the commit so i can do a live testing? the current doesnt work anyway? :-)

**Comment by pergolafabio** [comment]
sorry, a bit new to me :-)

but i placed the new version from @felipecrs , placed in local addon folders

but on config page, i can only see the port config, where can i define all the setttings that are needed?
So when i start it now, it says below, json missing, but quite normal, because i didnt enter any config?

![image](https://user-images.githubusercontent.com/43251136/152542984-add86fef-daf9-4755-acad-c59e0d04d598.png)


![image](https://user-images.githubusercontent.com/43251136/152542766-77ce63b8-5d26-404a-8de6-116756541234.png)

**Comment by pergolafabio** [comment]
or @felipecrs , can i add your repository? maybe you can release some kind of beta? that makes easier for me

**Comment by felipecrs** [comment]
@pergolafabio configure at /config/risco-mqtt.json

**Comment by pergolafabio** [comment]
hmm, placed that json file on 3 places, doesnt start :-(

placed it in 
config\config.json
addons\risco-mqtt-local-addon-config
addons\risco-mqtt-local-addon-config\risco-mqtt-local-addon


```
Loading config from: /usr/src/app/config.json
file /usr/src/app/config.json does not exist
```

**Comment by felipecrs** [comment]
Did you try the one which I said?

**Comment by pergolafabio** [comment]
Yes, the risco-mqtt.json in the config share, but I try again next week

**Comment by felipecrs** [comment]
@vanackej why `host_network` needs to be enabled?

**Comment by felipecrs** [comment]
@pergolafabio try from my fork instead, at least until @vanackej does not merge my PR.

https://github.com/felipecrs/risco-mqtt-local

You can add the repo directly in your Home Assistant, no need to clone to /addons and test locally.

**Comment by pergolafabio** [comment]
Much appreciated, will test Monday, have a nice weekend

**Comment by felipecrs** [comment]
Oh, and btw, make sure to create the config file before you start the addon for the first time, otherwise it will probably fail because the config file does not exist.

I think you can start by using the contents of the sample config in the root of this repository.

**Comment by pergolafabio** [comment]
ok, started the add-on, but u get error below

![image](https://user-images.githubusercontent.com/43251136/152687730-1faf72e9-e47d-4d8d-a3cb-db74086467a8.png)

**Comment by felipecrs** [comment]
I think it should work now.

**Comment by pergolafabio** [comment]
looking good indeed!!! thnx!!

i had to use a static IP now for mqtt, before i could use localhost, but doesnt  mather offcourse

![image](https://user-images.githubusercontent.com/43251136/152697474-d649a8e1-8223-4316-bfab-aa5d2d694335.png)

**Comment by felipecrs** [comment]
I think you can use "homeassistant" as the IP.

**Comment by pergolafabio** [comment]
yes, that works indeed
seems you are also creating a default json file in the config

working great, much appreciated!! Much better now to stay up to date with updates
