### ISSUE TITLE
Add ability to bypass a zone

### ISSUE THREAD

**Issue by markxroberts** [vanackej/risco-mqtt-local#12]
Thanks for a terrific project.
It is working well for me.
I would love an option to bypass a zone.  This would then be a complete replacement for RiscoCloud integration in HA for me.  If it exists and I've missed it, my apologies!

**Comment by vanackej** [comment]
I was also thinking about it.
But I'm not sure how to map this notion to HA entities.
Zones are mapped to binary_sensor in HA. I can't attach the toggle action to them directly.
Should I introduce an additional companion switch for each zone ? https://www.home-assistant.io/integrations/switch.mqtt/

**Comment by markxroberts** [comment]
Hi
Yes, I think a companion switch for each zone would be a good idea.
Currently I have lots of input booleans that bypass a zone when switch to on, and unbypass when switched to off.  I reset all these to off once the alarm is unset as the bypass zone function only lasts until the alarm is next set/unset.
Presumably this behaviour is also possible through MQTT?
Best wishes
Mark
