### ISSUE TITLE
Bind mount failed

### ISSUE THREAD

**Issue by mrbarbz** [vanackej/risco-mqtt-local#13]
I'm running Docker on Synology 918+ and when I put the below docker run command  via SSH using putty 

 **_docker run -v $(pwd)/config.json:/volume1/docker/riscolocal/config/config.json vanackej/risco-mqtt-local_**

I get this error

**_docker: Error response from daemon: Bind mount failed: '/root/config.json' does not exists.
ERRO[0003] error waiting for container: context canceled_**

What am I doing wrong?
I have created the config.json and placed it config folder

**Comment by vanackej** [comment]
Your volume mounting is inverted First part is the path in the host, second part is the path in the container.
Just open your terminal in `/volume1/docker/riscolocal/config` and use docker run command as documented in README.

**Comment by mrbarbz** [comment]
works thanks
