### ISSUE TITLE
ProSYS Plus issue

### ISSUE THREAD

**Issue by ob1w4nken0b1** [vanackej/risco-mqtt-local#16]
Hi,

I've been testing this addon on ProSYS Plus with the example json config, I've been able to connect to the panel but the log shows this timeout loop on startup and after a while it just throws an error and stops. 
Any ideas?
<img width="987" alt="timeot loop" src="https://user-images.githubusercontent.com/96317655/153449863-fe644ae4-0907-4977-baf5-0e0b43a210de.png">

**Comment by vanackej** [comment]
Hi

Can you either close & reopen this issue or at least update your issue description providing all informations asked in the new issue template please ?

Thx

**Comment by ob1w4nken0b1** [comment]
i reopened this issue following your instructions
