### ISSUE TITLE
No MQTT

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#2]
Hey, as discussed on other thread, i dont see any mqtt ?

what could be wrong? i dont see any mqtt login in my add-on eiter, that means the addon is not even trying to connect and send data?
what could be wrong?
this is my config.json i use for the add-on

```
{
  "name": "Risco MQTT Bridge",
  "version": "2",
  "slug": "risco-mqtt-local",
  "description": "Risco Local/Cloud Integration",
  "startup": "application",
  "arch": ["aarch64", "amd64", "armhf", "armv7", "i386"],
  "host_network": true,
  "ports": {
    "33000/tcp": 33000
  },	
  "log": "debug",
  "panel": {
    "Panel_IP": "192.168.0.232",
    "Panel_Port": 1000, 
    "Panel_Password": 5678,
    "Panel_Id": "0001",
    "WatchDogInterval": 10000,
	"Disable_RiscoCloud":  true,
	"Enable_RiscoCloud":  true,
	"DiscoverCode":  false,
	"SocketMode": "proxy",
	"ListeningPort": 33000,
	"CloudPort": 33000,
	"CloudUrl": "www.riscocloud.com"
  },
  "mqtt": {
    "url": "mqtt://localhost:1833",
    "username": "xxx",
    "password": "xxx",
    "zone-label-prefix": ""
  }  
}
```

i actually stuff bout the zones, but i dont see there mqtt messages either?

```
Command CRC Value : A18D
CRC Ok
Data from Panel, need to send an ACK.
Sending Ack.
Command CRC Value : 5E37
Received From Panel : ZSTT5=O---------
Zone Status datas.
Zones Status Changed :
 Zone Id 5
 New Status: Open
```

**Comment by pergolafabio** [comment]
omg, i defined wrong port 1833 instead of 1883

**Comment by vanackej** [comment]
Ok, I'll have a look to add logs when connection fails anyway

**Comment by pergolafabio** [comment]
its fixed, mqtt working, i just mistyped!! :-)

**Comment by pergolafabio** [comment]
indeed, addling logs when it fails, would be usefull :)

**Comment by vanackej** [comment]
Yes I know, but I want to keep the ticket open to think to add error logs when mqtt connection fails ;-)

**Comment by pergolafabio** [comment]
i also opened this ticket : https://github.com/TJForc/risco-lan-bridge/issues/13

if i restart the docker, it fails , if i restart agaitn , it succeeds
you any idea? maybe you can intercept that message or something? and restart the proxy if needed?

**Comment by vanackej** [comment]
Sorry, no idea. I don't have the issue with direct socket mode. I think it's more an issue to track in the communication library than here

**Comment by pergolafabio** [comment]
yeah, thats why i created indeed the issue there, thnx anyway
docker is now running since a few hours, gonna check later the response of the sensor, not at home now
but should be faster now then polling :-)

everything is auto discoverd in HA

ps: a hacs version would be nice :-) ; i now created a local addon instead

**Comment by vanackej** [comment]
I just released a new version with improved logging and MQTT reconnection management

**Comment by pergolafabio** [comment]
thnx!
