### ISSUE TITLE
Debugging possible?

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#3]
hey @vanackej 

as you know i have proxy enabled, i have the docker running for 1 day now, works verry good
but this night i got a mail notification that the panel was offline for a 10 minutes

can i debug this? how can i save thos debug to a file while running the addon?

thnx

**Comment by vanackej** [comment]
If running as docker container, you can check the logs using docker logs
command. If running as Home assistant add-on, I think there is a view in
the supervisor to consult addons logs.
You can change the log level of the library using the config.json parameter
(see project Readme)

Le mer. 1 déc. 2021 à 08:52, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
Hi, yes, running as add-on, there is indeed a supervirsior log , but thats limited to 1 screen only
so the error that was last night, is already passed :-)

debug is indeed enabled already, so there is a lot 

not sure if i can save the supervisor log to a file

**Comment by pergolafabio** [comment]
hmm, seems not possible to save add-on logs to file
can you maybe make an option to save the file inside the docker itself? if i see the error , then i can access the container and grab the file 

usefull for debugging/testing, especially in the beginning of the project

**Comment by pergolafabio** [comment]
i have also turned off the watchdog now, not sure if the addon was stopped when the issue occured

**Comment by vanackej** [comment]
No sorry, I won't go this way for logs (at least for now). It would make
logging configuration much more complicated, and would break what I
consider best practices in logs management for containers : The process
outputs everything to standard output, and the caller is in charge of
storing the output in whatever location he wants.

You can simply run the Docker container outside of Home assistant (command
line in project Readme) and redirect the output to the file you want (
docker cmd > mylogfile.txt )

Le mer. 1 déc. 2021 à 10:09, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok, np , will have a look to start manually...

thnx

**Comment by pergolafabio** [comment]
ok, found something, seems the addon is saving log in background

so i saved it with this command:
`docker logs -f addon_local_risco-mqtt-local &> /config/risco.log &`
 not sure who is keeping the log files, and if they are only temp
maybe they are gone after a reboot or cleared after some days

created new issue thread here... not sure if its related to this add-on or the  proxy

https://github.com/TJForc/risco-lan-bridge/issues/14
