### ISSUE TITLE
Connect two or more panels

### ISSUE THREAD

**Issue by gfuentesv** [vanackej/risco-mqtt-local#33]
Hello,
is posible connect two o more panels?

Thanks.

**Comment by vanackej** [comment]
Hello,
Not at the moment.
The best way for now would be to launch 2 separate docker containers or npm processes.

**Comment by gfuentesv** [comment]
Ok, Thanks.

Best Regards.

**Comment by vanackej** [comment]
In fact it would not be possible for now because alarm topic prefix is not configurable.
@gfuentesv  Do you have any coding skills to try to make a PR ?
If not, I will try to have a look, but I don't know when I'll have some time to spend on it

**Comment by gfuentesv** [comment]
Ok, i launch separate process, and the problem is alarm topic prefix.
i don't coding skills, sorry
The ideal would be to be able to configure the alarm topic prefix in the configuration file risco-mqtt.json.
Please, if you can give me any solution, let me know.
Thank you very much.

**Comment by gfuentesv** [comment]
I change the panel_id, in the panel and in the configuration file, but this does not affect to alarm topic prefix.

**Comment by markxroberts** [comment]
I've produced a fix for you to test.
The js file is here: [https://github.com/markxroberts/risco-mqtt-local-js/blob/main/risco-mqtt-local.js](url)

You'll need to replace the same file in your file installation.  It usually lives in /app/dist/lib

You'll need to update your config.json to include (as a separate line, **not** part of the MQTT config):

```
"mqtt_alarm_topic": "your alarm topic",
```

If it works for you (I can't test as I only have one installation), then let me know and I'll open a pull request to he main library.

**Comment by gfuentesv** [comment]
Hello, and thanks.
but
I can't find my file installation in /app/dist/lib.
I can't find /app/dist/lib

I installed the addon automatically.

**Comment by markxroberts** [comment]
It will be hiding somewhere in your setup so it might be worth looking elsewhere.  If you can’t find it you’ll need to wait for the pull request.  I’ll try to do that in the next day or two. @vanackej will then need to approve.

**Comment by gfuentesv** [comment]
I can't find.
I wait for the pull request.

Thank you very much.

**Comment by gfuentesv** [comment]
Hello, 
I find other way to work, now i have connect 4 panels.
Run one VM HomeAssistan for each risco panel, with risco-bride and mosquitto broker addons,
in the main HomeAssistan config mosquitto broker for bridge all mosquitto broker of  other isntances, and config in each bride to remap topic.
Work fine, but mqtt discovery not work, the sensors have to add manually.

But I like test the markxroberts solution.

Thanks.
