### ISSUE TITLE
Update issue to 0.4.3

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#44]
Hey @vanackej 

I saw an update for addon, but it doesn't start anymore with error below

Image ghcr.io/vanackej/risco-mqtt-local-addon-amd64:0.4.3 does not exist for addon_c774f33c_risco-mqtt-local-addon

**Comment by vanackej** [comment]
Yeah the addon declaration was updated before the actual docker image was
available.
Just uninstall/reinstall the addon

Le lun. 4 juil. 2022 à 21:54, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
Indeed , it's now running again, thnx , appreciated
