### ISSUE TITLE
Provide ARMv7 image

### ISSUE THREAD

**Issue by swiergot** [vanackej/risco-mqtt-local#49]
Please consider providing official addon images for ARMv7 (i.e. 32-bit RPi).

I have built such image myself and it's been running without issues on my RPi 3B+.

https://hub.docker.com/layers/swiergot/risco-mqtt-local/v0.4.2/images/sha256-4fd6a9fe4bacda0911603038a2eaaddbb9f0e8a6321b5a769ff21e227d7845eb?context=explore

**Comment by vanackej** [comment]
Available in 0.5.0-beta.2
Please confirm this is ok and close the issue then

**Comment by swiergot** [comment]
Seems to be working fine, thank you!
