### ISSUE TITLE
Errors on running

### ISSUE THREAD

**Issue by markxroberts** [vanackej/risco-mqtt-local#5]
Running this as a package under official node.js docker build
2 errors on running the package with command:

npx @vanackej/risco-mqtt-local

/home/node/app/node_modules/.bin/risco-mqtt-local: 1: use strict: not found
/home/node/app/node_modules/.bin/risco-mqtt-local: 2: Syntax error: word unexpected (expecting ")")

Can you help?

**Comment by vanackej** [comment]
Hi,

It seems npx execution is broken since I migrated to typescript build.
If I understand well, you repackaged the library in a custom Docker
container. Why don't you use the Docker image provided by the project ? It
works fine (internally running the library with yarn install + node, not
npx)

For npx usage, I'll have a look maybe this weekend or next week, no time
right now sorry

Le mar. 14 déc. 2021 à 11:47, markxroberts ***@***.***> a
écrit :

**Comment by vanackej** [comment]
Ok, finally it was really easy to fix. 
I just released 0.2.1 that works again with npx.

**Comment by markxroberts** [comment]
Hi
Thanks for getting back to me.
I tried that, but couldn’t work out how to map the config.json file.
It looks for it at /usr/src/app/config.json, but if I map that folder to a local folder, it can’t find the rest of the node…
I only have very limited knowledge of these things, so I don’t have the understanding to debug properly!
Thanks again
Mark

**Comment by markxroberts** [comment]
Hi
Thanks for the update. It works perfectly now.
Would love to be able to use the native docker though…
Thanks again 
Mark

Mark Roberts

On 14 Dec 2021, at 18:25, Johann Vanackere ***@***.***> wrote:

﻿
Ok, finally it was really easy to fix.
I just released 0.2.1 that works again with npx.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by vanackej** [comment]
The command to run for Docker is in the documentation :
https://github.com/vanackej/risco-mqtt-local#using-docker-image
Ensure to be in the directory  containing your config.json when you run the
command, and it should run just fine


Le mar. 14 déc. 2021 à 22:52, markxroberts ***@***.***> a
écrit :

> Hi
> Thanks for the update. It works perfectly now.
> Would love to be able to use the native docker though…
> Thanks again
> Mark
>
> Mark Roberts
>
