### ISSUE TITLE
Add delay between socket connect and RMT command

### ISSUE THREAD

**Issue by kkmaslowski** [vanackej/risco-mqtt-local#6]
I cannot get working my LightSys 2 with RW132IP.
I think it can be fixed with:
https://github.com/TJForc/risco-lan-bridge/pull/12 
Can you add delay to your code for older panels?

I see that code loops and panel timeouts. When I stop container it instantly logs panel model, info about partitions, etc and exits. So it's working for a sec before exiting container.

Discussion about problem: https://github.com/TJForc/risco-lan-bridge/issues/10

**Comment by vanackej** [comment]
Is that a different problem from your other ticket ? 
I fixed a bug related to timeout management and automatically resend data : https://github.com/vanackej/risco-lan-bridge/commit/9abbca7da42523ac9dd0aa33fa62e988e2452360#diff-ec40811138a0238eb01fa58694f0e4abfb9e8bdde8037a94ca22946570db4089R258
I think that was the root cause for the issue you mentionned and it is not necessary to add a pause at startup like done in the other library.

**Comment by kkmaslowski** [comment]
Yes, this ticket is for local mode (without proxy/cloud). I cannot get working both modes (local or proxy).

**Comment by vanackej** [comment]
Can you disable proxy mode, enable debug logs, attempt to connect to your
panel and send me your logs ?

Let's first try to make it work in direct connection mode, then adding
Cloud connectivity once panel connection is ok.

Le mar. 21 déc. 2021 à 20:39, Kamil Maslowski ***@***.***> a
écrit :

**Comment by kkmaslowski** [comment]
I pasted it here: https://0bin.net/paste/3AcNLa4s#K65xjpoFnwPmK9gpY7xQ0BgI-5esjfZaxvQ3fJh+trB
I stopped container at 8:02 and after stopping it send data to mqtt. Without stopping it 
loops with errors like above:
```
[2,17,50,54,72,66,124,10,241,41,160,213,224,228,12,190,59,95,121,97,133,34,154,150,106,252,61,235,145,22,204,52,47,108,46,198,203,167,163,228,143,56,173,196,206,190,171,201,213,152,192,16,16,102,226,20,139,80,135,209,61,60,90,124,95,248,212,107,122,178,70,81,44,31,30,235,70,202,161,162,194,154,22,239,16,16,3]
12/21/2021, 7:59:55 PM [debug] Command CRC Value : 0CED
12/21/2021, 7:59:55 PM [debug] CRC Not Ok
12/21/2021, 7:59:56 PM [debug] Command[03] 'CUSTLST??' Timeout!!!
12/21/2021, 7:59:56 PM [debug] Sending Command: CUSTLST??
12/21/2021, 7:59:56 PM [debug] Command CRC Value : A04E
12/21/2021, 7:59:56 PM [debug] Command[03] Sent.
12/21/2021, 7:59:56 PM [debug] Sequence[3] Data Sent : CUSTLST??
12/21/2021, 7:59:56 PM [debug] Received data Buffer : [2,17,50,54,72,66,124,10,241,41,160,213,224,228,12,190,59,95,121,97,133,34,154,150,106,252,61,235,145,22,204,52,47,108,46,198,203,167,163,228,143,56,173,196,206,190,171,201,213,152,192,16,16,102,226,20,139,80,135,209,61,60,90,124,95,248,212,107,122,178,70,81,44,31,30,235,70,202,161,162,194,154,22,239,16,16,3]
12/21/2021, 7:59:56 PM [debug] Command CRC Value : 0CED
12/21/2021, 7:59:56 PM [debug] CRC Not Ok
12/21/2021, 7:59:56 PM [debug] Command[03] 'CUSTLST??' Timeout!!!
12/21/2021, 7:59:56 PM [debug] Sending Command: CUSTLST??
12/21/2021, 7:59:56 PM [debug] Command CRC Value : A04E
12/21/2021, 7:59:56 PM [debug] Command[03] Sent.
12/21/2021, 7:59:56 PM [debug] Sequence[3] Data Sent : CUSTLST??
12/21/2021, 7:59:56 PM [debug] Received data Buffer :
```
