### ISSUE TITLE
RiscoCloud Socket Destroyed

### ISSUE THREAD

**Issue by pergolafabio** [vanackej/risco-mqtt-local#9]
Hi @vanackej , updated to new  0.3.1, did some restarts of the add-on, but still seeing error below , if this error occurs, then the add-on is in a crashed state...

thnx for looking into it

```

1/3/2022, 1:39:18 PM [debug] [Panel => Cloud] Forwarding panel packet to cloud: [2,19,57,51,4,6,0,5,0,16,3,0,0,0,23,54,49,70,51,3]
1/3/2022, 1:39:18 PM [error] Panel Socket Closed.
1/3/2022, 1:39:18 PM [debug] RiscoCloud Socket Destroyed.
1/3/2022, 1:39:18 PM [error] TCP Socket Disconnected
1/3/2022, 1:39:29 PM [verbose] Start Connection to Panel
1/3/2022, 1:39:29 PM [debug] TCP Socket is already created, Connect It
1/3/2022, 1:39:29 PM [debug] TCP Socket must be created now
1/3/2022, 1:39:29 PM [info] Listening on IP :: and Port 33000
1/3/2022, 1:39:29 PM [info] Waiting for panel incoming connection... This can take up to 1 or 2 minutes
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
AssertionError [ERR_ASSERTION]: Expected 'isPanelSocketConnected' to be true, but received false. Socket failed to connect after 100ms delay
    at new AssertionError (node:internal/assert/assertion_error:466:5)
    at assertIsTrue (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/Assertions.js:15:15)
    at RiscoProxyTCPSocket.<anonymous> (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoBaseSocket.js:522:43)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/tslib/tslib.js:113:16)
    at RiscoProxyTCPSocket.panelConnect (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoBaseSocket.js:521:38)
    at RiscoProxyTCPSocket.<anonymous> (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoProxySocket.js:157:32)
    at Generator.next (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: undefined
}
```

**Comment by vanackej** [comment]
Please provide full log from startup. Only with this part I can't have a look at what happened

**Comment by pergolafabio** [comment]
Ok, I try to reproduce

**Comment by pergolafabio** [comment]
that buffer data, is that confidential?

**Comment by vanackej** [comment]
Not sure, but no I don't think

Le lun. 3 janv. 2022 à 14:35, pergolafabio ***@***.***> a
écrit :

**Comment by pergolafabio** [comment]
ok, i removed it just in case

```
1/3/2022, 2:35:05 PM [[34mdebug[39m] Pseudo Buffer Created for Panel Id(0001): 
1/3/2022, 2:35:05 PM [[34mdebug[39m] Local GMT Timezone is : +01:00
1/3/2022, 2:35:05 PM [[32minfo[39m] autoConnect enabled, starting communication
1/3/2022, 2:35:05 PM [[36mverbose[39m] Start Connection to Panel
1/3/2022, 2:35:05 PM [[34mdebug[39m] TCP Socket is not already created, Create It
1/3/2022, 2:35:05 PM [[34mdebug[39m] TCP Socket must be created now
1/3/2022, 2:35:05 PM [[32minfo[39m] Connecting to mqtt server: mqtt://localhost:1883
1/3/2022, 2:35:05 PM [[32minfo[39m] Listening on IP :: and Port 33000
1/3/2022, 2:35:05 PM [[32minfo[39m] Waiting for panel incoming connection... This can take up to 1 or 2 minutes
1/3/2022, 2:35:05 PM [[32minfo[39m] Connected on mqtt server: mqtt://localhost:1883
1/3/2022, 2:35:05 PM [[32minfo[39m] Panel is not connected, waiting
1/3/2022, 2:35:19 PM [[32minfo[39m] Incoming connection from panel received
1/3/2022, 2:35:20 PM [[34mdebug[39m] RiscoCloud Socket: connect
1/3/2022, 2:35:20 PM [[32minfo[39m] RiscoCloud Socket: ready
1/3/2022, 2:35:20 PM [[32minfo[39m] Setting a timer for panel connection in 30000 ms
1/3/2022, 2:35:20 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:20 PM [[34mdebug[39m] [Cloud => Panel] Forwarding Cloud data Buffer to panel: 
1/3/2022, 2:35:21 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:23 PM [[34mdebug[39m] [Cloud => Panel] Forwarding Cloud data Buffer to panel: 
1/3/2022, 2:35:23 PM [[34mdebug[39m] [Cloud => Panel] Forwarding Cloud data Buffer to panel: 
1/3/2022, 2:35:27 PM [[34mdebug[39m] [Cloud => Panel] Forwarding Cloud data Buffer to panel: 
1/3/2022, 2:35:27 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:27 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:27 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:32 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:33 PM [[34mdebug[39m] [Cloud => Panel] Forwarding Cloud data Buffer to panel: 
1/3/2022, 2:35:33 PM [[34mdebug[39m] [Panel => Cloud] Forwarding panel packet to cloud: 
1/3/2022, 2:35:33 PM [[31merror[39m] Panel Socket Closed.
1/3/2022, 2:35:33 PM [[34mdebug[39m] RiscoCloud Socket Destroyed.
1/3/2022, 2:35:33 PM [[31merror[39m] TCP Socket Disconnected
1/3/2022, 2:35:43 PM [[36mverbose[39m] Start Connection to Panel
1/3/2022, 2:35:43 PM [[34mdebug[39m] TCP Socket is already created, Connect It
1/3/2022, 2:35:43 PM [[34mdebug[39m] TCP Socket must be created now
1/3/2022, 2:35:43 PM [[32minfo[39m] Listening on IP :: and Port 33000
1/3/2022, 2:35:43 PM [[32minfo[39m] Waiting for panel incoming connection... This can take up to 1 or 2 minutes
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^
AssertionError [ERR_ASSERTION]: Expected 'isPanelSocketConnected' to be true, but received false. Socket failed to connect after 100ms delay
    at new AssertionError (node:internal/assert/assertion_error:466:5)
    at assertIsTrue (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/Assertions.js:15:15)
    at RiscoProxyTCPSocket.<anonymous> (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoBaseSocket.js:522:43)
    at Generator.next (<anonymous>)
    at /usr/src/app/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at __awaiter (/usr/src/app/node_modules/tslib/tslib.js:113:16)
    at RiscoProxyTCPSocket.panelConnect (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoBaseSocket.js:521:38)
    at RiscoProxyTCPSocket.<anonymous> (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoProxySocket.js:157:32)
    at Generator.next (<anonymous>) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: undefined,
  expected: undefined,
  operator: undefined
}
```

**Comment by vanackej** [comment]
Try 0.3.2

**Comment by pergolafabio** [comment]
ok :-)

colors are gone from log? :)

**Comment by pergolafabio** [comment]
i now see this error : 


1/3/2022, 3:55:30 PM [debug] Command[1] Emitting expected command response
1/3/2022, 3:55:30 PM [verbose] Command[1] Received data from panel: ACK
1/3/2022, 3:55:30 PM [debug] Command[1] SendCommand receive this response : ACK
1/3/2022, 3:55:30 PM [verbose] Command[2] Sending Command: LCL
1/3/2022, 3:55:30 PM [debug] Command[2] Writing command buffer to socket: [2,48,50,76,67,76,23,65,53,65,70,3]
1/3/2022, 3:55:30 PM [debug] Command[2] Data Sent : LCL
1/3/2022, 3:55:31 PM [debug] [Panel => Bridge] Received unencrypted data Buffer from Panel : [2,48,50,65,67,75,23,51,57,65,70,3]
1/3/2022, 3:55:31 PM [debug] Received data Buffer : [2,48,50,65,67,75,23,51,57,65,70,3]
1/3/2022, 3:55:31 PM [debug] Command[2] CRC Value : 39AF
1/3/2022, 3:55:31 PM [debug] Command[2] CRC Ok
1/3/2022, 3:55:31 PM [debug] Command[2] Command response from Panel
1/3/2022, 3:55:31 PM [debug] Command[2] Emitting expected command response
1/3/2022, 3:55:31 PM [verbose] Command[2] Received data from panel: ACK
1/3/2022, 3:55:31 PM [debug] Command[2] SendCommand receive this response : ACK
1/3/2022, 3:55:31 PM [debug] LCL command result OK
1/3/2022, 3:55:31 PM [verbose] Setting up encryption using Panel Id
1/3/2022, 3:55:31 PM [verbose] Command[3] Sending Command: CUSTLST?
1/3/2022, 3:55:31 PM [debug] Command[3] Writing command buffer to socket: [2,17,50,54,72,66,124,10,241,41,160,215,199,148,115,188,60,3]
1/3/2022, 3:55:31 PM [debug] Command[3] Data Sent : CUSTLST?
1/3/2022, 3:55:31 PM [debug] [Panel => Bridge] Received encrypted data Buffer from Panel : [2,17,50,54,72,66,124,10,241,41,160,213,224,228,12,190,59,95,121,97,133,34,154,150,106,252,61,235,145,22,204,52,47,108,46,198,203,167,163,228,143,56,173,196,206,190,171,201,213,152,192,16,16,102,226,20,139,80,135,209,61,60,90,124,95,248,212,107,122,178,70,81,44,31,30,235,70,202,161,162,238,154,17,239,67,154,99,151,125,3]
1/3/2022, 3:55:31 PM [debug] Received data Buffer : [2,17,50,54,72,66,124,10,241,41,160,213,224,228,12,190,59,95,121,97,133,34,154,150,106,252,61,235,145,22,204,52,47,108,46,198,203,167,163,228,143,56,173,196,206,190,171,201,213,152,192,16,16,102,226,20,139,80,135,209,61,60,90,124,95,248,212,107,122,178,70,81,44,31,30,235,70,202,161,162,238,154,17,239,67,154,99,151,125,3]
1/3/2022, 3:55:31 PM [debug] Command[3] CRC Value : 2259
1/3/2022, 3:55:31 PM [debug] Command[3] CRC Ok
1/3/2022, 3:55:31 PM [verbose] Command[3] inCryptTest enabled, emitting response without checks
1/3/2022, 3:55:31 PM [debug] Command[3] SendCommand receive this response : CUSTLST=0EN;0IT;0IL;0HU;0UK;0SP;0PL;0GR;0BR;0RU;0NL;0FR;0CN;0DK;0CZ;0AU;0TH;0DE
1/3/2022, 3:55:31 PM [debug] cryptTableTester response: CUSTLST=0EN;0IT;0IL;0HU;0UK;0SP;0PL;0GR;0BR;0RU;0NL;0FR;0CN;0DK;0CZ;0AU;0TH;0DE
1/3/2022, 3:55:31 PM [verbose] Connection to the control panel successfully established.
1/3/2022, 3:55:31 PM [debug] Risco Panel Connected.
1/3/2022, 3:55:31 PM [verbose] Command[4] Sending Command: PNLCNF
1/3/2022, 3:55:31 PM [debug] Command[4] Writing command buffer to socket: [2,17,50,49,91,89,99,29,243,60,227,171,149,144,119,3]
1/3/2022, 3:55:31 PM [debug] Command[4] Data Sent : PNLCNF
1/3/2022, 3:55:31 PM [debug] [Panel => Bridge] Received encrypted data Buffer from Panel : [2,17,50,49,91,89,99,29,243,60,201,186,128,149,113,183,28,37,21,98,131,3]
1/3/2022, 3:55:31 PM [debug] Received data Buffer : [2,17,50,49,91,89,99,29,243,60,201,186,128,149,113,183,28,37,21,98,131,3]
1/3/2022, 3:55:31 PM [debug] Command[4] CRC Value : 3886
1/3/2022, 3:55:31 PM [debug] Command[4] CRC Ok
1/3/2022, 3:55:31 PM [debug] Command[4] Command response from Panel
1/3/2022, 3:55:31 PM [debug] Command[4] Emitting expected command response
1/3/2022, 3:55:31 PM [verbose] Command[4] Received data from panel: PNLCNF=RP432
1/3/2022, 3:55:31 PM [debug] Command[4] SendCommand receive this response : PNLCNF=RP432
1/3/2022, 3:55:31 PM [verbose] Command[5] Sending Command: FSVER?
1/3/2022, 3:55:31 PM [debug] Command[5] Writing command buffer to socket: [2,17,50,48,77,68,121,27,239,69,227,221,226,144,0,3]
1/3/2022, 3:55:31 PM [debug] Command[5] Data Sent : FSVER?
1/3/2022, 3:55:31 PM [debug] [Panel => Bridge] Received encrypted data Buffer from Panel : [2,17,50,48,77,68,121,27,239,71,198,198,231,145,98,180,61,57,29,109,154,90,226,141,122,148,101,218,182,115,182,77,39,3]
1/3/2022, 3:55:31 PM [debug] Received data Buffer : [2,17,50,48,77,68,121,27,239,71,198,198,231,145,98,180,61,57,29,109,154,90,226,141,122,148,101,218,182,115,182,77,39,3]
1/3/2022, 3:55:31 PM [debug] Command[5] CRC Value : 01B8
1/3/2022, 3:55:31 PM [debug] Command[5] CRC Ok
1/3/2022, 3:55:31 PM [debug] Command[5] Command response from Panel
1/3/2022, 3:55:31 PM [debug] Command[5] Emitting expected command response
1/3/2022, 3:55:31 PM [verbose] Command[5] Received data from panel: FSVER=2.70 16/07/14   
1/3/2022, 3:55:31 PM [debug] Command[5] SendCommand receive this response : FSVER=2.70 16/07/14   
1/3/2022, 3:55:31 PM [debug] Panel Firmware Version : 2.70
1/3/2022, 3:55:31 PM [info] Panel info: LightSys/RP432, FW 2.70
1/3/2022, 3:55:31 PM [info] Panel options: 4 parts, 32 zones, 14 outputs, Pir Cam support: false
1/3/2022, 3:55:31 PM [debug] Checking the configuration of the control unit.
1/3/2022, 3:55:31 PM [debug] Beginning of device discovery.
1/3/2022, 3:55:31 PM [debug] Retrieving System's Information.
1/3/2022, 3:55:31 PM [verbose] Command[6] Sending Command: SYSLBL?
1/3/2022, 3:55:31 PM [debug] Command[6] Writing command buffer to socket: [2,17,50,51,88,78,124,18,255,54,203,255,232,152,115,196,3]
1/3/2022, 3:55:31 PM [debug] Command[6] Data Sent : SYSLBL?
1/3/2022, 3:55:31 PM [debug] [Panel => Bridge] Received encrypted data Buffer from Panel : [2,17,50,51,88,78,124,18,255,54,201,169,188,192,48,232,43,69,84,41,193,14,179,192,77,240,95,148,231,3]
1/3/2022, 3:55:31 PM [debug] Received data Buffer : [2,17,50,51,88,78,124,18,255,54,201,169,188,192,48,232,43,69,84,41,193,14,179,192,77,240,95,148,231,3]
1/3/2022, 3:55:31 PM [debug] Command[6] CRC Value : D7DF
1/3/2022, 3:55:31 PM [debug] Command[6] CRC Ok
1/3/2022, 3:55:31 PM [debug] Command[6] Command response from Panel
1/3/2022, 3:55:31 PM [debug] Command[6] Emitting expected command response
1/3/2022, 3:55:31 PM [verbose] Command[6] Received data from panel: SYSLBL=Alarm Systeem
1/3/2022, 3:55:31 PM [debug] Command[6] SendCommand receive this response : SYSLBL=Alarm Systeem
1/3/2022, 3:55:31 PM [verbose] Command[7] Sending Command: SSTT?
1/3/2022, 3:55:31 PM [debug] Command[7] Writing command buffer to socket: [2,17,50,50,88,68,123,10,130,109,181,172,232,229,3]
1/3/2022, 3:55:31 PM [debug] Command[7] Data Sent : SSTT?
1/3/2022, 3:55:31 PM [error] Panel Socket Closed.
1/3/2022, 3:55:31 PM [debug] RiscoCloud Socket Destroyed.
1/3/2022, 3:55:31 PM [error] TCP Socket Disconnected
1/3/2022, 3:55:36 PM [warn] Command[7] 'SSTT?' Timeout
1/3/2022, 3:55:36 PM [debug] Command[7] retrying with a new command Id
1/3/2022, 3:55:36 PM [warn] sendCommand(SSTT?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [debug] Retrieving the configuration of the Zones.
1/3/2022, 3:55:36 PM [warn] sendCommand(ZTYPE*1:8?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZPART&*1:8?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZAREA&*1:8?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLBL*1:8?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZSTT*1:8?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP1?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP2?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP3?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP4?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP5?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP6?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP7?): Socket is destroyed, ignoring command
1/3/2022, 3:55:36 PM [warn] sendCommand(ZLNKTYP8?): Socket is destroyed, ignoring command
/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoComm.js:527
                    Item.Label = ZLabels[j].trim();
                                            ^
TypeError: Cannot read properties of undefined (reading 'trim')
    at RiscoComm.<anonymous> (/usr/src/app/node_modules/@vanackej/risco-lan-bridge/dist/RiscoComm.js:527:45)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/src/app/node_modules/tslib/tslib.js:114:62)

**Comment by vanackej** [comment]
Colorized logs are now disabled by default (I want to avoid unreadable issues reports/logs attachements). Can be activated by setting `"logColorize": true` in `config.json`

Your panel is closing the socket connection randomly in the middle of discovery process. Don't know why. No time right now to attempt to manage this case, for now try multiple restarts until it "works", I'll have a look later

**Comment by pergolafabio** [comment]
ok, fair enough :-)

thnx in advance, let me know if you update a new feature later

because i also think that socket destroyed message can happen any time

**Comment by vanackej** [comment]
Socket disconnection are managed as gracefully as possible during the rest of the usage of the library, but especially during startup phase, it's more problematic and not well handled yet

**Comment by pergolafabio** [comment]
isnt it as easy, when you see exception, to just restart the process? :-)

**Comment by vanackej** [comment]
Can you try with 0.3.6 please ?

**Comment by pergolafabio** [comment]
i think it looks better now, did about 10  x restarts, 2 times i had the socket destroyed, but now i did the retry, and docker didnt crash... so it looks good

gonna close ticket for now, much appreciated!


```
2/21/2022, 8:46:33 AM [debug] [Panel => Cloud] Forwarding panel packet to cloud: [2,19,57,48,4,56,0,5,0,4,1,0,1,0,80,101,114,103,111,108,97,32,81,117,105,110,116,101,110,115,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,23,53,51,50,51,3]
2/21/2022, 8:46:33 AM [error] Panel Socket Closed.
2/21/2022, 8:46:33 AM [debug] RiscoCloud Socket Destroyed.
2/21/2022, 8:46:33 AM [info] TCP Socket Disconnected
2/21/2022, 8:46:33 AM [info] Automatic reconnection will be attempted in 10000 ms
2/21/2022, 8:46:43 AM [verbose] Start Connection to Panel
2/21/2022, 8:46:43 AM [debug] A TCP Socket is already created, clearing its listeners 
2/21/2022, 8:46:43 AM [debug] TCP Socket is not already created, Create It
2/21/2022, 8:46:43 AM [debug] TCP Socket must be created now
2/21/2022, 8:46:43 AM [info] Listening on IP :: and Port 33000
2/21/2022, 8:46:43 AM [info] Waiting for panel incoming connection... This can take up to 1 or 2 minutes
2/21/2022, 8:46:49 AM [warn] Panel Socket not connected, aborting panel connection sequence
2/21/2022, 8:49:04 AM [info] Incoming connection from panel received
2/21/2022, 8:49:04 AM [debug] RiscoCloud Socket: connect
2/21/2022, 8:49:04 AM [info] RiscoCloud Socket: ready
2/21/2022, 8:49:04 AM [info] Setting a timer for panel connection in 30000 ms
2/21/2022, 8:49:04 AM [debug] [Panel => Cloud] Forwarding panel packet to cloud: 
```
